
[CPU-CLUSTER0-MONITOR]
algo_type           monitor
sampling            1000
sensor              cpuss-0
thresholds          72000        80000        88000
thresholds_clr      67000        75000        83000
actions             cpu-cluster0 cpu-cluster0 cpu-cluster0
action_info         1785600      1555200      1324800

[CPU-CLUSTER1-MONITOR]
algo_type           monitor
sampling            1000
sensor              cpuss-1
thresholds          74000        82000        90000
thresholds_clr      69000        77000        85000
actions             cpu-cluster1 cpu-cluster1 cpu-cluster1
action_info         2208000      1804800      1440000

[CPU-CLUSTER2-MONITOR]
algo_type           monitor
sampling            1000
sensor              cpuss-1
thresholds          76000        84000        92000
thresholds_clr      71000        79000        87000
actions             cpu-cluster2 cpu-cluster2 cpu-cluster2
action_info         2572800      2150400      1708800

[GPU-MONITOR]
algo_type           monitor
sampling            1000
sensor              gpuss-0
thresholds          80000        87000        93000
thresholds_clr      75000        82000        88000
actions             gpu          gpu          gpu
action_info         684000000    585000000    430000000

[SKIN-MONITOR]
algo_type           monitor
sampling            3000
sensor              xo-therm
thresholds          44000        49000        54000
thresholds_clr      40000        45000        50000
actions             cpu-cluster2+gpu \
                    cpu-cluster1+cpu-cluster2+gpu \
                    cpu-cluster1+cpu-cluster2+gpu+display-fps
action_info         2150400+684000000 \
                    1804800+2150400+585000000 \
                    1555200+1708800+430000000+1

[MONITOR-BACKLIGHT]
algo_type           monitor
sensor              xo-therm
actions             panel0-backlight
sampling            5000
thresholds          52000
thresholds_clr      47000
action_info         180

[MODEM-MONITOR]
algo_type           monitor
sampling            5000
sensor              mdmss-0
thresholds          76000        82000        88000
thresholds_clr      71000        77000        83000
actions             modem        modem        modem
action_info         1            2            3

[CAMERA-MONITOR]
algo_type           monitor
sampling            2000
sensor              camera-0
thresholds          72000        80000
thresholds_clr      67000        75000
actions             cpu-cluster1+cpu-cluster2+gpu \
                    cpu-cluster1+cpu-cluster2+gpu
action_info         2208000+2150400+585000000 \
                    1804800+1708800+430000000

[WIFI-MONITOR]
algo_type           monitor
sampling            10000
sensor              wifi_therm
thresholds          68000
thresholds_clr      62000
actions             wlan
action_info         1
